# Configuration file used by the product-file-sync.yml workflow
settings:
  pull_request:
    title: 'chore: sync files with `<%- repository %>` [skip ci]'
    labels:
      - chore
    merge: 
      mode: admin
      strategy: squash
      delete_branch: true      
  commit: 
    format: '<%- prefix %>: <%- subject %>'
    prefix: 'chore'
    subject: 'sync files with `<%- repository %>` [skip ci]'
patterns:
  # Important, committing to the .github/workflows folder 
  # require the user to have "workflow" scope on the token
  # https://github.com/octokit/rest.js/issues/368
  - files:
      - .github/release.yml
      - from: .github/ISSUE_TEMPLATE
        to: .github/ISSUE_TEMPLATE
        exclude:
          - '**/custom_*/*'        
      - from: .github/ISSUE_TEMPLATE/custom_product
        to: .github/ISSUE_TEMPLATE
      - .github/workflows/delivery-issue-chores.yml
      - .github/workflows/delivery-pr-chores.yml
    delete_files:
      - .github/ISSUE_TEMPLATE/cloud-change-request.yml
    repositories:
      # This list contains repositories not maintained by the product team
      # but for which there is a desire to maintain the same default files
      # than product team repositories, for for example "community" modules
      # maintained by the support team.
      - Jahia/user-cleanup-tool@main


